apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-data-analysis-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8000
    name: http
  - port: {{ .Values.service.mcpPort }}
    targetPort: 8001
    name: mcp-sse
  selector:
    app: data-analysis-service
